apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: consul

namespace: consul

# Enable Helm chart support
helmCharts:
  - name: consul
    repo: https://helm.releases.hashicorp.com
    version: 1.4.8
    namespace: consul
    releaseName: consul
    valuesInline:
      consul:
        backup:
          Enabled: false
        global:
          argocd:
            enabled: true
          enabled: false
          name: consul
          datacenter: dev-am01
          image: "hashicorp/consul:1.18.2"
          acls:
            manageSystemACLs: true
        server:
          enabled: true
          replicas: 1
          storage: 5Gi
          connect: false
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
          disruptionBudget:
            enabled: false
        client:
          enabled: false
        dns:
          enabled: false
        ui:
          enabled: true
          service:
            type: ClusterIP
        connectInject:
          enabled: false
        syncCatalog:
          enabled: false
        meshGateway:
          enabled: false
        ingressGateways:
          enabled: false
        terminatingGateways:
          enabled: false
