# KEDA ScaledObject for Canary Demo — Scale based on HTTP request rate.
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rollouts-demo-canary-scaler
  namespace: rollouts-demo
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: rollouts-demo-canary
  minReplicaCount: 2
  maxReplicaCount: 5
  cooldownPeriod: 300
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://kube-prometheus-stack-prometheus.monitoring:9090
      metricName: http_requests_per_second
      query: |
        sum(rate(http_requests_total{job="rollouts-demo-canary"}[30s])) by (job)
      threshold: "100"
---
# KEDA ScaledObject for Blue-Green Demo — Scale based on HTTP request rate.
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rollouts-demo-blue-green-scaler
  namespace: rollouts-demo
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: rollouts-demo-blue-green
  minReplicaCount: 2
  maxReplicaCount: 5
  cooldownPeriod: 300
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://kube-prometheus-stack-prometheus.monitoring:9090
      metricName: http_requests_per_second
      query: |
        sum(rate(http_requests_total{job="rollouts-demo-blue-green"}[30s])) by (job)
      threshold: "100"
