apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: consul-local

namespace: consul

resources:
  - ../../base

namePrefix: consul-local-

patches:
  - path: consul-patch.yaml
