apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-ui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://github.com/punit144/kubernetes-learn.git
    targetRevision: main
    path: clusters/colima/local-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
