apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: localhost-tls
  namespace: default
spec:
  secretName: localhost-tls-secret
  duration: 8760h
  renewBefore: 720h
  commonName: localhost
  dnsNames:
    - localhost
    - "*.localhost"
    - 127.0.0.1
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
